config/routes.rb
Rails.application.routes.draw do
  # get 'homes/top' => 'homes#top'
  # 以下は省略形（上記と同じ意味になる）
  # HTTPメソッド'URL' => 'コントローラ#アクション'
  # URLと'コントローラ名#アクション名'の形が同じになる場合は、この部分を省略することができる
  get 'top' => 'homes#top'

  # resources：ルーティングの記述を短縮できる
  # resourcesメソッド：ルーティングを一括して自動生成してくれる
  # listsコントローラの同じ名前のアクションに紐づく形で、以下のルーティングを自動生成してくれる。
  # → new, show, index, edit, create, destroy, update
  resources :lists

  # get 'lists/new'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # post 'lists' => 'lists#create'
  # get 'lists' => 'lists#index'

  # # ../lists/1や../lists/3に該当する
  # # URLに投稿データのidを含める（表示する投稿データを判別するため）
  # # このidはshowアクション内にparams[:id]と記述することで取得できる
  # # as:オプション：名前付きルート
  # get 'lists/:id' => 'lists#show', as: 'list'

  # # 「,」と「:」の後ろにスペースを入れること
  # get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'

  # # PATCH：更新の場合のHTTPメソッド（POST：新規投稿の場合）
  # patch 'lists/:id' => 'lists#update', as: 'update_list'

  # # 削除機能destroyアクション用
  # delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  # ActiveStorageを使って画像を表示する際には、
  # どのモデルに対して画像を使うのかを宣言する必要があります。
  # 以下の記述により、Listモデルにtitleとbodyに加えて
  # 画像を扱うためのimageカラムが追記されたかのように扱うことが出来ます。
  has_one_attached :image

  # バリデーションの設定：モデルのファイルに設定内容を記述
  # validatesで対象とする項目を指定、入力されたデータのpresence（存在）をチェック
  # true：データが存在しなければならないという設定になる
  validates :title, presence: true
  validates :body, presence: true

  # 「rails c」を試すときはimageのバリデーションをコメントアウト
  # 理由：rails cで画像を扱う場合は複雑になるため
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    #Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @list = List.new
  end

  def create
    # データを受け取り新規登録するためのインスタンス作成
    @list = List.new(list_params)
    # データをDBに保存するためのsaveメソッド実行
    # saveメソッド：呼び出したModelインスタンスをDBへ保存する

    # モデルファイルに記述したバリデーションの結果を検出
    if @list.save
      # redirect_to '/top'を削除して、以下コードに変更
      # 詳細画面へリダイレクト
      redirect_to list_path(@list.id)
    else
      # 「render :アクション名」で同じコントローラの別アクションのViewを表示できる
      # saveメソッドで保存に失敗した場合、エラーメッセージが@list内に追加される
      # 以下のrenderの部分でredirect_toを使うとnewアクション内で再度@list = List.new が実行され、
      # @listが上書きされてエラーメッセージが消えてしまう。
      # 基本的には、エラーメッセージを扱う際にはrender、それ以外はredirect_toを扱うと覚える。
      render :new #バリデーション結果がfalseなら、新規投稿ページを再表示させる
    end
  end

  # 一覧画面用（投稿したList全てを表示）
  def index
    # allはメソッドの一種
    # モデルがやりとりしているDBのテーブル内の全レコードを取得
    # Listモデルがやりとりしているlistsテーブルの全レコードを取得
    @lists = List.all
  end

  # 詳細画面用
  def show
    # 詳細画面で呼び出される投稿データは、URLの/lists/:id内の:idで判別する
    # findメソッド：引数に一致するidカラムのレコードを取得する
    @list = List.find(params[:id])
  end

  # 編集画面用
  def edit
    @list = List.find(params[:id])
  end

  # 更新機能用
  # 対応するビューはなし。更新処理後はshowアクションにリダイレクト。
  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  # 削除機能用
  # ビューの「削除」ボタンをクリックすると、削除リストのid付きでURLが送信されます。
  # 送られてきた削除idを元にレコードが探され、そのレコードを削除します。
  def destroy
    list = List.find(params[:id]) #データ（レコード）を1件取得
    list.destroy #データ（レコード）を削除
    redirect_to '/lists' #投稿一覧画面へリダイレクト
  end

  # privateの行より後に定義されたメソッドは、アクションとして認識されなくなり、URLと対応できなくなる
  private

  # ストロングパラメータ
  # マスアサインメント脆弱性を防ぐ（保存カラムを限定することにより）
  # params：formから送られてくるデータが中に入っている
  # require：モデル名を指定する
  # permit：保存を許可するカラムを指定する

  # privateメソッドの名前：「モデル名_params」とすることが多い
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--application.html.erbは全てのビューに反映されるHTMLファイル-->
<!--そのため全ビュー共通の「ヘッダー・フッター」を記述するのに適している-->
<html>
  <head>
    <title>SampleAppDemo</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline">All Lists</h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<!--「model:」と「@list」の間にスペースを入れること-->
<%= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>

<h4>タイトル</h4>
<%= f.text_field :title %>

<h4>本文</h4>
<%= f.text_area :body %>

<%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
  <% @lists.each do |list| %>
    <div class="list-box">
      <% if list.image.attached? %>
        <!--「size:」の後ろにはスペースを入れること-->
        <%= image_tag list.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
      <% end %>
      <div class="list-comment">
        <!--Listモデルのbodyカラムに入っているデータを呼び出している-->
        <span class="list-body"><%= list.body %></span>
        <span class="list-title"><%= link_to list.title, list_path(list.id) %></span>
      </div>
    </div>
  <% end %>
</div>


<!--以下は10章までの記述-->

<!--<h1>投稿一覧</h1>-->
<!-- @lists.each do |list| %>-->
<!--  <p>タイトル</p>-->
  <!--link_toメソッド：リンクを設定する-->
  <!--構文：link_to 表示させるテキスト,リンク先URL[,オプション]-->
<!--  <span>-->
<!--    <= link_to list.title, list_path(list.id) %>-->
<!--  </span>-->
  <!--image_tagヘルパー：HTMLのimgタグを生成する-->
  <!--listモデルに紐づいているimageをimage_tagに渡すことで画像を表示することができる-->
<!--  <p>画像</p>-->
  <!--imageが存在していればlist.imageを表示、なければno_imageを表示-->
  <!--attached：画像が存在していればtrue、存在していなければfalseを返す-->
<!--  < if list.image.attached? %>-->
<!--    <= image_tag list.image, size: "200x200" %>-->
<!--  < else %>-->
<!--    <= image_tag 'no_image', size: "200x200" %>-->
<!--  < end %>-->
<!--< end %>-->

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<!--エラー内容の表示部分-->
<!--errorsメソッド：モデルにバリデーションをかけたときに、発生したエラーの内容を確認できる-->
<!--any?：エラーが発生しているかどうかを判定できる-->
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <!--full_messages：エラーの内容を出力できる。エラー文は配列で保存されているためeachを使う-->
    <% @list.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!--form_withにオプション追記-->
<%= form_with model: @list, url:'/lists', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <h4>画像</h4>
  <!--「file_field」はファイルの投稿をするためのフィールドなので、-->
  <!--画像ファイル以外の全てのファイル（音声ファイルや動画ファイルなど）も投稿できてします。-->
  <!--そのため「accept: "image/*"」を使い、画像ファイルしか投稿できないようにしている。-->
  <%= f.file_field :image, accept: "image/*" %>

  <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
<% if @list.image.attached? %>
    <%= image_tag @list.image, size: "300x300" %>
<% else %>
    <%= image_tag 'no_image', size: "300x300" %>
<% end %>

<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>